# Generated by Django 5.1.3 on 2024-11-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="turn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
