# Generated by Django 5.1.3 on 2024-12-01 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_profile_draws_profile_losts_alter_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("games_creator_won", models.IntegerField(default=0)),
                ("games_opponent_won", models.IntegerField(default=0)),
                ("total_games", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.game"
                    ),
                ),
            ],
        ),
    ]
