# Generated by Django 5.1.3 on 2024-12-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_gamestats"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestats",
            name="is_creator_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gamestats",
            name="is_opponent_online",
            field=models.BooleanField(default=False),
        ),
    ]
